language: ruby
rvm:
  - "2.0.0" 
env: TEST_DATABASE_URL=postgres://postgres@locahost/travispopup RAILS_ENV=test AWS_ACCESS_KEY_ID=fake AWS_SECRET_ACCESS_KEY=fake AWS_BUCKET=fake IA_ACCESS_KEY_ID=fake IA_SECRET_ACCESS_KEY=fake SECRET_TOKEN=fakefakefakefakefakefakefakefakefakefakefakefakefakefakefakefake
before_script:
  - rake db:create db:migrate
bundler_args: --without development assets
services:
  - elasticsearch
notifications:
  email:
    - popuparchive-tech@prx.org
